const media = [
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img24.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img4.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img5.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img6.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img7.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/electrical-img.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/electrical-img3.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/electrical-img4.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/electrical-img5.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img8.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img9.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img10.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img11.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img12.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img13.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img14.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img15.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img20.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img21.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img22.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img23.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img25.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/assets/portfolio/light-img26.jpeg'},
    //{id:'', type:'image', category:'electrical', path:'/src/assets/portfolio/light-img16.jpeg'},
    //{id:'', type:'image', category:'electrical', path:'/src/assets/portfolio/light-img17.jpeg'},
    {id:'', type:'image', category:'electrical', path:'/src/assets/portfolio/light-img18.jpeg'},

    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img1.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img2.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img3.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img4.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img5.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img6.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img7.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img8.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img9.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img10.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img11.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img12.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img13.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img14.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img15.jpeg'},
    {id:'', type:'image', category:'cctv', path:'/assets/portfolio/camera-img16.jpeg'},

    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img.jpeg'},
    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img2.jpeg'},
    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img3.jpeg'},
    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img4.jpeg'},
    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img5.jpeg'},
    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img6.jpeg'},
    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img7.jpeg'},
    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img8.jpeg'},
    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img9.jpeg'},
    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img10.jpeg'},
    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img11.jpeg'},
    {id:'', type:'image', category:'maintenance', path:'/assets/portfolio/maintenance-img12.jpeg'},

    //{id:'', type:'video', category:'electrical', path:'/src/assets/portfolio/light-vid.mp4'},
   // {id:'', type:'video', category:'electrical', path:'/src/assets/portfolio/light-vid6.mp4'},
    //{id:'', type:'video', category:'electrical', path:'/src/assets/portfolio/light-vid3.mp4'},
    //{id:'', type:'video', category:'electrical', path:'/src/assets/portfolio/light-vid7.mp4'},
    //{id:'', type:'video', category:'electrical', path:'/src/assets/portfolio/light-vid8.mp4'},

    //{id:'', type:'video', category:'maintenance', path:'/src/assets/portfolio/maintenance-vid.mp4'},
    //{id:'', type:'video', category:'maintenance', path:'/src/assets/portfolio/maintenance-vid2.mp4'},
    //{id:'', type:'video', category:'maintenance', path:'/src/assets/portfolio/maintenance-vid3.mp4'},
    //{id:'', type:'video', category:'maintenance', path:'/src/assets/portfolio/maintenance-vid4.mp4'},
   // {id:'', type:'video', category:'electrical', path:'/src/assets/portfolio/light-vid5.mp4'},

]

export default  media